// KidPix offline service worker.
// Precaches every app asset so the app runs fully offline after the first load.
// Handles HTTP Range requests from cache so <audio> sound effects work offline on iOS.
const CACHE = 'kidpix-offline-v1';
const ASSETS = [
  './',
  'index.html',
  '404.html',
  'manifest.webmanifest',
  'apple-touch-icon.png',
  'icon-192.png',
  'icon-512.png',
  'app.js',
  'kidpix.css',
  'img/bl1.png',
  'img/bl2.png',
  'img/br-starburst.png',
  'img/br10.png',
  'img/br11.png',
  'img/br12.png',
  'img/br13.png',
  'img/br14.png',
  'img/br15.png',
  'img/br16.png',
  'img/br18.png',
  'img/br19.png',
  'img/br20.png',
  'img/br21.png',
  'img/br23.png',
  'img/br6.png',
  'img/br7.png',
  'img/br8.png',
  'img/br9.png',
  'img/cursor-fill-bucket.png',
  'img/cursor-guy-meh.png',
  'img/cursor-guy-smile.png',
  'img/cursor-guy-wow.png',
  'img/cursor-paint-brush.png',
  'img/cursor-pencil.png',
  'img/cursor-tnt-0.png',
  'img/cursor-tnt-1.png',
  'img/cursor-tnt-anim.gif',
  'img/kidpix-doorbell-graphic-0.png',
  'img/kidpix-doorbell-graphic-1.png',
  'img/kidpix-guy.png',
  'img/kidpix-lrg.png',
  'img/kidpix-mixer-pattern-206.png',
  'img/kidpix-mixer-pattern-207.png',
  'img/kidpix-mixer-pattern-208.png',
  'img/kidpix-mixer-pattern-209.png',
  'img/kidpix-mixer-pattern-210.png',
  'img/kidpix-mixer-pattern-211.png',
  'img/kidpix-mixer-pattern-212.png',
  'img/kidpix-mixer-pattern-213.png',
  'img/kidpix-mixer-pattern-214.png',
  'img/kidpix-mixer-pattern-215.png',
  'img/kidpix-mixer-pattern-216.png',
  'img/kidpix-mixer-pattern-217.png',
  'img/kidpix-mixer-pattern-218.png',
  'img/kidpix-mixer-pattern-219.png',
  'img/kidpix-mixer-pattern-220.png',
  'img/kidpix-mixer-pattern-221.png',
  'img/kidpix-mixer-pattern-222.png',
  'img/kidpix-mixer-pattern-223.png',
  'img/kidpix-mixer-pattern-224.png',
  'img/kidpix-mixer-pattern-225.png',
  'img/kidpix-mixer-pattern-226.png',
  'img/kidpix-mixer-pattern-227.png',
  'img/kidpix-mixer-pattern-228.png',
  'img/kidpix-mixer-pattern-229.png',
  'img/kidpix-mixer-pattern-230.png',
  'img/kidpix-spritesheet-0.png',
  'img/kidpix-spritesheet-0b.png',
  'img/kidpix-spritesheet-1.png',
  'img/kidpix-spritesheet-2.png',
  'img/kidpix-spritesheet-3.png',
  'img/kidpix-spritesheet-4.png',
  'img/kidpix-spritesheet-5.png',
  'img/kidpix-spritesheet-6.png',
  'img/kidpix-spritesheet-7.png',
  'img/kidpix-spritesheet-8.png',
  'img/kidpix.png',
  'img/kp-h-bear.png',
  'img/kp-h-bison.png',
  'img/kp-h-corn.png',
  'img/kp-h-eye.png',
  'img/kp-h-fox.png',
  'img/kp-h-horse.png',
  'img/kp-h-hummingbird.png',
  'img/kp-h-ladybug.png',
  'img/kp-h-lion.png',
  'img/kp-h-magnet.png',
  'img/kp-h-moth.png',
  'img/kp-h-octopus.png',
  'img/kp-m_27.png',
  'img/kp-m_28.png',
  'img/kp-m_29.png',
  'img/kp-m_30.png',
  'img/kp-m_31.png',
  'img/kp-m_32.png',
  'img/kp-m_33.png',
  'img/kp-m_34.png',
  'img/kp-m_35.png',
  'img/kp-m_36.png',
  'img/kp-m_37.png',
  'img/kp-m_38.png',
  'img/kp-m_39.png',
  'img/kp-mlogo.png',
  'img/kp-sticker-1.png',
  'img/kp-sticker-2.png',
  'img/kp-sticker-3.png',
  'img/kp-sticker-4.png',
  'img/kp-sticker-5.png',
  'img/kp-sticker-6.png',
  'img/pw1.png',
  'img/pw2.png',
  'img/pw3.png',
  'img/pw4.png',
  'img/pw5.png',
  'img/pw6.png',
  'img/spray-br-2.png',
  'img/spray-br-3.png',
  'img/spray-br-4.png',
  'img/spray-br-5.png',
  'img/spray-br-6.png',
  'img/spray-br-7.png',
  'img/tool-menu-wacky-brush-70.png',
  'img/tool-menu-wacky-brush-71.png',
  'img/tool-menu-wacky-brush-72.png',
  'img/tool-menu-wacky-brush-73.png',
  'img/tool-menu-wacky-brush-74.png',
  'img/tool-menu-wacky-brush-75.png',
  'img/tool-menu-wacky-brush-76.png',
  'img/tool-menu-wacky-brush-77.png',
  'img/tool-menu-wacky-brush-78.png',
  'img/tool-menu-wacky-brush-79.png',
  'img/tool-menu-wacky-brush-80.png',
  'img/tool-menu-wacky-brush-81.png',
  'img/tool-menu-wacky-brush-82.png',
  'img/tool-menu-wacky-brush-83.png',
  'img/tool-menu-wacky-brush-84.png',
  'img/tool-menu-wacky-brush-85.png',
  'img/tool-menu-wacky-brush-86.png',
  'img/tool-menu-wacky-brush-87.png',
  'img/tool-menu-wacky-brush-88.png',
  'img/tool-menu-wacky-brush-89.png',
  'img/tool-menu-wacky-brush-90.png',
  'img/tool-menu-wacky-brush-91.png',
  'img/tool-menu-wacky-brush-92.png',
  'img/tool-menu-wacky-brush-93.png',
  'img/tool-menu-wacky-brush-94.png',
  'img/tool-menu-wacky-brush-95.png',
  'img/tool-menu-wacky-brush-96.png',
  'img/tool-menu-wacky-brush-97.png',
  'img/tool-ptr-bucket-fill.png',
  'img/tool-submenu-eraser-178.png',
  'img/tool-submenu-eraser-179.png',
  'img/tool-submenu-eraser-180.png',
  'img/tool-submenu-eraser-181.png',
  'img/tool-submenu-eraser-182.png',
  'img/tool-submenu-eraser-183.png',
  'img/tool-submenu-eraser-184.png',
  'img/tool-submenu-eraser-185.png',
  'img/tool-submenu-eraser-186.png',
  'img/tool-submenu-eraser-187.png',
  'img/tool-submenu-eraser-188.png',
  'img/tool-submenu-eraser-189.png',
  'img/tool-submenu-eraser-190.png',
  'img/tool-submenu-eraser-191.png',
  'img/tool-submenu-pencil-size-1.png',
  'img/tool-submenu-pencil-size-2.png',
  'img/tool-submenu-pencil-size-3.png',
  'img/tool-submenu-pencil-size-4.png',
  'img/tool-submenu-pencil-size-5.png',
  'img/tool-submenu-pencil-size-6.png',
  'img/tool-submenu-truck-192.png',
  'img/tool-submenu-truck-193.png',
  'img/tool-submenu-truck-194.png',
  'img/tool-submenu-truck-195.png',
  'img/tool-submenu-truck-196.png',
  'img/tool-submenu-truck-197.png',
  'img/tool-submenu-truck-198.png',
  'img/tool-submenu-truck-199.png',
  'img/tool-submenu-truck-200.png',
  'img/tool-submenu-truck-201.png',
  'img/tool-submenu-truck-202.png',
  'img/tool-submenu-truck-203.png',
  'img/tool-submenu-truck-204.png',
  'img/tool-submenu-truck-205.png',
  'img/tool-submenu-wacky-mixer-164.png',
  'img/tool-submenu-wacky-mixer-165.png',
  'img/tool-submenu-wacky-mixer-166.png',
  'img/tool-submenu-wacky-mixer-167.png',
  'img/tool-submenu-wacky-mixer-168.png',
  'img/tool-submenu-wacky-mixer-169.png',
  'img/tool-submenu-wacky-mixer-170.png',
  'img/tool-submenu-wacky-mixer-171.png',
  'img/tool-submenu-wacky-mixer-172.png',
  'img/tool-submenu-wacky-mixer-173.png',
  'img/tool-submenu-wacky-mixer-174.png',
  'img/tool-submenu-wacky-mixer-175.png',
  'img/tool-submenu-wacky-mixer-176.png',
  'img/tool-submenu-wacky-mixer-177.png',
  'img/tool-unknown.png',
  'sndmp3/bubble-pop-2WAVSOUND.R_0004edd3.wav.mp3',
  'sndmp3/bubble-pop-3WAVSOUND.R_0004fccd.wav.mp3',
  'sndmp3/bubble-pop-4WAVSOUND.R_0004f480.wav.mp3',
  'sndmp3/bubble-pop-WAVSOUND.R_000031f6.wav.mp3',
  'sndmp3/bubble-pop-WAVSOUND.R_00050452.wav.mp3',
  'sndmp3/chord.wav.mp3',
  'sndmp3/electric-mixer-inverter-rolling-sound-WAVSOUND.R_0001fcfa.wav.mp3',
  'sndmp3/electric-mixer-pip-drum-crash-1WAVSOUND.R_0002d96e.wav.mp3',
  'sndmp3/electric-mixer-shadow-boxes-WAVSOUND.R_0002a07a.wav.mp3',
  'sndmp3/electric-mixer-venetian-WAVSOUND.R_0001df56.wav.mp3',
  'sndmp3/electric-mixer-wallpaper-jitter-boingo-WAVSOUND.R_00024fcc.wav.mp3',
  'sndmp3/english/alpha-a-WAVSOUND.R_0007d8f2.wav.mp3',
  'sndmp3/english/alpha-b-WAVSOUND.R_0007ee1f.wav.mp3',
  'sndmp3/english/alpha-c-WAVSOUND.R_000803fc.wav.mp3',
  'sndmp3/english/alpha-d-WAVSOUND.R_000815df.wav.mp3',
  'sndmp3/english/alpha-e-WAVSOUND.R_00082fcc.wav.mp3',
  'sndmp3/english/alpha-f-WAVSOUND.R_00084629.wav.mp3',
  'sndmp3/english/alpha-g-WAVSOUND.R_000853d0.wav.mp3',
  'sndmp3/english/alpha-h-WAVSOUND.R_00086213.wav.mp3',
  'sndmp3/english/alpha-i-WAVSOUND.R_00087a00.wav.mp3',
  'sndmp3/english/alpha-j-WAVSOUND.R_00088ced.wav.mp3',
  'sndmp3/english/alpha-k-WAVSOUND.R_0008a72e.wav.mp3',
  'sndmp3/english/alpha-l-WAVSOUND.R_0008bda3.wav.mp3',
  'sndmp3/english/alpha-m-WAVSOUND.R_0008d0f8.wav.mp3',
  'sndmp3/english/alpha-n-WAVSOUND.R_0008e695.wav.mp3',
  'sndmp3/english/alpha-o-WAVSOUND.R_0008fcaa.wav.mp3',
  'sndmp3/english/alpha-p-WAVSOUND.R_00091bdb.wav.mp3',
  'sndmp3/english/alpha-q-WAVSOUND.R_00092aee.wav.mp3',
  'sndmp3/english/alpha-r-WAVSOUND.R_0009639f.wav.mp3',
  'sndmp3/english/alpha-s-WAVSOUND.R_00097948.wav.mp3',
  'sndmp3/english/alpha-t-WAVSOUND.R_00099085.wav.mp3',
  'sndmp3/english/alpha-u-WAVSOUND.R_0009a406.wav.mp3',
  'sndmp3/english/alpha-v-WAVSOUND.R_0009bbcf.wav.mp3',
  'sndmp3/english/alpha-w-WAVSOUND.R_0009d8cc.wav.mp3',
  'sndmp3/english/alpha-x-WAVSOUND.R_0009ff1d.wav.mp3',
  'sndmp3/english/alpha-y-WAVSOUND.R_000a177a.wav.mp3',
  'sndmp3/english/alpha-z-WAVSOUND.R_000a2fe7.wav.mp3',
  'sndmp3/english/number-0-WAVSOUND.R_000a7832.wav.mp3',
  'sndmp3/english/number-1-WAVSOUND.R_000a9f1f.wav.mp3',
  'sndmp3/english/number-2-WAVSOUND.R_000ab58c.wav.mp3',
  'sndmp3/english/number-3-WAVSOUND.R_000aca17.wav.mp3',
  'sndmp3/english/number-4-WAVSOUND.R_000ae7a4.wav.mp3',
  'sndmp3/english/number-5-WAVSOUND.R_000afbb1.wav.mp3',
  'sndmp3/english/number-6-WAVSOUND.R_000b205a.wav.mp3',
  'sndmp3/english/number-7-WAVSOUND.R_000b43e7.wav.mp3',
  'sndmp3/english/number-8-WAVSOUND.002_000555ac.wav.mp3',
  'sndmp3/english/number-9-WAVSOUND.R_000b7db1.wav.mp3',
  'sndmp3/english/number-ampersand-WAVSOUND.R_000be96f.wav.mp3',
  'sndmp3/english/number-eclamation-WAVSOUND.R_000a5774.wav.mp3',
  'sndmp3/english/number-equals-WAVSOUND.R_000bce22.wav.mp3',
  'sndmp3/english/number-minus-WAVSOUND.R_000bb0e5.wav.mp3',
  'sndmp3/english/number-plus-WAVSOUND.R_000b9a58.wav.mp3',
  'sndmp3/english/number-question-mark-WAVSOUND.R_000a661d.wav.mp3',
  'sndmp3/eraser-tool-fade-2WAVSOUND.R_0002f58b.wav.mp3',
  'sndmp3/eraser-tool-split-0-dingdong-WAVSOUND.R_00050aef.wav.mp3',
  'sndmp3/eraser-tool-split-1-door-creaking-WAVSOUND.R_00056699.wav.mp3',
  'sndmp3/eraser-tool-split-3-wowwww-WAVSOUND.R_00052ccc.wav.mp3',
  'sndmp3/flood0.wav.mp3',
  'sndmp3/kidpix-eraser-doorbell-ding-dong.wav.mp3',
  'sndmp3/kidpix-eraser-doorbell-door-creak.wav.mp3',
  'sndmp3/kidpix-eraser-doorbell-wwoooowwww.wav.mp3',
  'sndmp3/kidpix-menu-click-main-tools.wav.mp3',
  'sndmp3/kidpix-menu-click-submenu-color.wav.mp3',
  'sndmp3/kidpix-menu-click-submenu-options.wav.mp3',
  'sndmp3/kidpix-submenu-brush-bubbly.wav.mp3',
  'sndmp3/kidpix-submenu-brush-cards.wav.mp3',
  'sndmp3/kidpix-submenu-brush-dots.wav.mp3',
  'sndmp3/kidpix-submenu-brush-fuzzer.wav.mp3',
  'sndmp3/kidpix-submenu-brush-guilloche.wav.mp3',
  'sndmp3/kidpix-submenu-brush-inverter.wav.mp3',
  'sndmp3/kidpix-submenu-brush-kaliediscope.wav.mp3',
  'sndmp3/kidpix-submenu-brush-leaky-pen.wav.mp3',
  'sndmp3/kidpix-submenu-brush-northern.wav.mp3',
  'sndmp3/kidpix-submenu-brush-owl.wav.mp3',
  'sndmp3/kidpix-submenu-brush-pies.wav.mp3',
  'sndmp3/kidpix-submenu-brush-pines.wav.mp3',
  'sndmp3/kidpix-submenu-brush-prints.wav.mp3',
  'sndmp3/kidpix-submenu-brush-rollingdots.wav.mp3',
  'sndmp3/kidpix-submenu-brush-shapes.wav.mp3',
  'sndmp3/kidpix-submenu-brush-spraypaint.wav.mp3',
  'sndmp3/kidpix-submenu-brush-stars.wav.mp3',
  'sndmp3/kidpix-submenu-brush-tree.wav.mp3',
  'sndmp3/kidpix-submenu-brush-twirly.wav.mp3',
  'sndmp3/kidpix-submenu-brush-xos.wav.mp3',
  'sndmp3/kidpix-submenu-brush-xy-during.wav.mp3',
  'sndmp3/kidpix-submenu-brush-xy-end.wav.mp3',
  'sndmp3/kidpix-submenu-brush-xy-start.wav.mp3',
  'sndmp3/kidpix-submenu-brush-zigzag.wav.mp3',
  'sndmp3/kidpix-submenu-brush-zoom.wav.mp3',
  'sndmp3/kidpix-tool-box-during-approx.wav.mp3',
  'sndmp3/kidpix-tool-circle-during-approx.wav.mp3',
  'sndmp3/kidpix-tool-eraser-tnt-explosion.wav.mp3',
  'sndmp3/kidpix-tool-line-during.wav.mp3',
  'sndmp3/kidpix-tool-line-end.wav.mp3',
  'sndmp3/kidpix-tool-line-start.wav.mp3',
  'sndmp3/kidpix-tool-pencil.wav.mp3',
  'sndmp3/kidpix-truck-skid.wav.mp3',
  'sndmp3/kidpix-truck-truckin-go.wav.mp3',
  'sndmp3/kidpix-truck-truckin.wav.mp3',
  'sndmp3/oops0.wav.mp3',
  'sndmp3/oops1.wav.mp3',
  'sndmp3/oops2.wav.mp3',
  'sndmp3/oops3.wav.mp3',
  'sndmp3/stamp0.wav.mp3',
  'sndmp3/western-gun-shot-twirl-WAVSOUND.R_0005ed70.wav.mp3',
  'static/banner.png',
  'static/belongsto.png',
  'static/jskidpix-ogcolor.png',
  'static/jskidpix-orig.png',
  'static/jskidpix.png',
  'static/kidpix10b.png',
  'static/splash.png',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Build a 206 Partial Content response from a fully-cached response.
// iOS Safari issues Range requests for <audio>; without this, offline sounds fail.
async function rangeFromCache(request, cachedResponse) {
  const buffer = await cachedResponse.arrayBuffer();
  const total = buffer.byteLength;
  const match = /bytes=(\d*)-(\d*)/.exec(request.headers.get('range') || '');
  let start = match && match[1] !== '' ? parseInt(match[1], 10) : 0;
  let end = match && match[2] !== '' ? parseInt(match[2], 10) : total - 1;
  if (isNaN(start) || start < 0) start = 0;
  if (isNaN(end) || end >= total) end = total - 1;
  if (start > end) start = 0;
  const chunk = buffer.slice(start, end + 1);
  return new Response(chunk, {
    status: 206,
    statusText: 'Partial Content',
    headers: {
      'Content-Type': cachedResponse.headers.get('Content-Type') || 'application/octet-stream',
      'Content-Range': 'bytes ' + start + '-' + end + '/' + total,
      'Content-Length': String(chunk.byteLength),
      'Accept-Ranges': 'bytes'
    }
  });
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });

    // Range request (audio) served from cache as a proper 206.
    if (request.headers.has('range') && cached) {
      return rangeFromCache(request, cached);
    }
    if (cached) return cached;

    // Not in cache: go to network, and cache same-origin successes for next time.
    try {
      const response = await fetch(request);
      const url = new URL(request.url);
      if (url.origin === self.location.origin && response && response.status === 200 && response.type === 'basic') {
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
      }
      return response;
    } catch (err) {
      // Offline and uncached: fall back to the app shell for navigations.
      if (request.mode === 'navigate') {
        return (await caches.match('index.html')) || (await caches.match('./')) || Response.error();
      }
      return Response.error();
    }
  })());
});
